version: '3'

services:
  web-server:
    container_name: web_server
    build: ./frontend
    tty: true
    stdin_open: true
    volumes:
      - ./frontend/src:/srv/gui
    ports:
      - '5001:5001'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    tty: true
    stdin_open: true
    # restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
